spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database-platform: ${DB_DIALECT}
    hibernate:
      ddl-auto: validate

server:
  forward-headers-strategy: native

unideb:
  backend:
    jwt-issuer: ${JWT_ISSUER}
    jwt-secret: ${JWT_SECRET}