spring:
  datasource:
    url: jdbc:h2:mem:devdb
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop

unideb:
  backend:
    jwt-issuer: "unideb.tech"
    jwt-secret: "DEV-SECRET!"
    jwt-expiration: 10