name: CI Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: temurin
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.9.0
    
    - name: Execute Gradle build
      run: ./gradlew build
